### ISSUE TITLE
Size of inline code in headings

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/quillt#24]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/5420529/110680413-93410c00-81a6-11eb-8021-c0e9592f1fa4.png">

https://rstudio-education.github.io/gradethis/reference/grade_this-objects.html

**Comment by cderv** [comment]
Oh that is indeed weird 😅 

edge case where you use function name in the title.

**Comment by cderv** [comment]
```css
h1 > code {
    font-size: inherit;
}
```
![image](https://user-images.githubusercontent.com/6791940/110680942-8689db80-81d9-11eb-9503-ed41e9ef2528.png)


?

**Comment by gadenbuie** [comment]
yeah that looks better. I'd recommend removing the background color too

**Comment by cderv** [comment]
And the color also maybe ? 
```css
h1 > code {
    font-size: inherit;
    background-color: inherit;
    color: inherit;
}
```
![image](https://user-images.githubusercontent.com/6791940/110682203-f9478680-81da-11eb-8e69-5ebb788aa6ed.png)
